#!/usr/bin/env bash
# Script that displays School 10 times, on the 9th iteration, displays Best School, then Hi on a new line
i=0
while [ $i -le 9 ]
do
	echo "Best School"
	if [ $i -eq 8 ]
	then
		echo "Hi"
	fi
	((i++))
done
